version: '3'

volumes:
  social_network_local_postgres_data: {}




services:
  postgres:
    image: postgres:latest
    container_name: social_network_local_postgres
    ports:
      - "5432:5432"
    volumes:
      - social_network_local_postgres_data:/var/lib/postgresql/data
    env_file:
      - .env