version: '3'

volumes:
  social_network_local_postgres_data: {}


services:
  postgres:
    image: postgres:latest
    container_name: social_network_local_postgres
    ports:
      - "5432:5432"
    volumes:
      - social_network_local_postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  web:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true