# Generated by Django 4.2.1 on 2023-05-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='replies',
            field=models.ManyToManyField(to='post.comment', verbose_name='replies'),
        ),
        migrations.AddField(
            model_name='comment',
            name='replies_count',
            field=models.IntegerField(default=0, verbose_name='Number of replies'),
        ),
    ]
